# BUILD
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . ./
RUN dotnet restore home-server.sln
RUN dotnet publish src/home-server.csproj -c Release -o bin/publish

# RUN
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine
WORKDIR /api
COPY --from=build /app/bin/publish .
ENV ASPNETCORE_HTTP_PORTS=80
# ASPNETCORE_HTTPS_PORTS=443
EXPOSE 80 443
CMD ["dotnet", "home-server.dll"]
