FROM node:lts-alpine as build
WORKDIR /app
COPY . ./
RUN yarn install --frozen-lockfile
RUN yarn ng build --configuration=production
FROM nginx:alpine
COPY --from=build /app/dist /client
COPY ./nginx.conf /etc/nginx/nginx.conf
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
