# BUILD
FROM node:lts-alpine as build
RUN corepack enable
WORKDIR /app
COPY . ./
RUN yarn install --immutable
RUN yarn build --configuration=production

# RUN
FROM nginx:mainline-alpine
COPY --from=build /app/dist /client
RUN rm -rf /etc/nginx/conf.d
RUN mkdir /etc/nginx/conf.d
COPY ./default.conf /etc/nginx/conf.d/
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
